name: hello

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Find and Build All Projects
      run: |
        for dir in $(find . -name Cargo.toml -exec dirname {} \;); do
          echo "Building in $dir"
          (cd $dir && cargo build --verbose)
        done
    - name: Find and Test All Projects
      run: |
        for dir in $(find . -name Cargo.toml -exec dirname {} \;); do
          echo "Testing in $dir"
          (cd $dir && cargo test --verbose)
        done
